---
plugin: amazon.aws.aws_ec2
regions:
  - eu-central-1

# 1. Hostname ke liye sirf 'ip-address' use karein
hostnames:
  - ip-address

# 2. Filter mein list format use karein
filters:
  instance-state-name: 
    - running

# 3. Compose mein hamesha underscores (_) use karein
compose:
  ansible_host: public_ip_address
  ansible_user: "'ubuntu'"
  ansible_ssh_private_key_file: "'/home/porwal-ji/bhawna/sessions/ansible_strategy/bhawna.pem'"

# 4. Groups banane ke liye
keyed_groups:
  - key: tags.role
    prefix: tag
